[language-server.ocaml]
command = "ocamllsp"

[language-server.typescript]
command = "typescript-language-server"

[language-server.jdtls]
command = "jdtls"

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java", "jav"]
roots = ["pom.xml", "build.gradle", "build.gradle.kts"]
language-servers = [ "jdtls" ]
indent = { tab-width = 4, unit = " " }

[[language]]
name = "ocaml"
scope = "source.ocaml"
injection-regex = "ocaml"
file-types = [ "ml" ]
indent = { tab-width = 4, unit = " " }
formatter = { command = "ocamlformat" , args = ["--stdin"] }
